server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coach_auth
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: "YOhVIILWnA9ZCbUShsWIzqlVpDhpKEaYGAAjnplCmU4=" #same across all services
  expirationMs: 900000         # 15 minutes access token
  refreshExpirationMs: 604800000 # 7 days refresh token
